server:
  port: 10011
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhuyunsheng93/leyou-config1.git
  rabbitmq:
    host: 192.168.0.127
    username: /leyou
    password: leyou
    virtual-host: /leyou
management:
  endpoints:
    web:
      exposure:
        exclude: bus-refresh
